# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.CharField(max_length=200, verbose_name='e-mail')),
                ('turno_aula', models.CharField(max_length=20, verbose_name='Turno')),
                ('matricula', models.CharField(max_length=14, unique=True, verbose_name='Matrincula')),
            ],
        ),
    ]
