# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 15:14
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appPonto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
            ],
            options={
                'permissions': (('view_porta', 'Can see porta'),),
            },
        ),
        migrations.CreateModel(
            name='Registro_porta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.TimeField(default=django.utils.timezone.now)),
                ('hora_saida', models.TimeField(default=django.utils.timezone.now)),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPortas.Porta', verbose_name='Porta')),
            ],
            options={
                'permissions': (('view_PermissaoPorta', 'Can see PermissaoPorta'),),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appPonto.Pessoa')),
            ],
            options={
                'permissions': (('view_usuario', 'Can see usuario'),),
            },
            bases=('appPonto.pessoa',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='porta',
            field=models.ManyToManyField(to='appPortas.Porta'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuario',
            field=models.ManyToManyField(to='appPortas.Usuario'),
        ),
    ]
