# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appPonto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
            options={
                'permissions': (('view_grupo', 'Can see grupo'),),
            },
        ),
        migrations.CreateModel(
            name='Pessoa_Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPortas.Grupo', verbose_name='Grupo')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPonto.Pessoa', verbose_name='Pessoa')),
            ],
            options={
                'permissions': (('view_pessoa_grupo', 'Can see pessoa_grupo'),),
            },
        ),
        migrations.CreateModel(
            name='Porta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('local', models.CharField(max_length=255, verbose_name='Local')),
            ],
            options={
                'permissions': (('view_porta', 'Can see porta'),),
            },
        ),
        migrations.CreateModel(
            name='Porta_Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPortas.Grupo', verbose_name='Grupo')),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPortas.Porta', verbose_name='Porta')),
            ],
            options={
                'permissions': (('view_porta_grupo', 'Can see porta_grupo'),),
            },
        ),
        migrations.CreateModel(
            name='Registro_porta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('hora_acesso', models.TimeField(default=django.utils.timezone.now)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPonto.Pessoa', verbose_name='Pessoa')),
                ('porta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPortas.Porta', verbose_name='Porta')),
            ],
            options={
                'permissions': (('view_Registro_porta', 'Can see Registro_porta'),),
            },
        ),
    ]
