# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 11:29
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appPonto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appPonto.Pessoa')),
                ('turno_aula', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespetino', 'Vespetino'), ('Noturno', 'Noturno')], max_length=30)),
            ],
            options={
                'permissions': (('view_aluno', 'Can see aluno'),),
            },
            bases=('appPonto.pessoa',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=200, verbose_name='local')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appalunos.Aluno', verbose_name='Aluno')),
            ],
            options={
                'permissions': (('view_relatorio_aluno', 'Can see relatorio aluno'), ('view_relatorioPonto_aluno', 'Can see relatorio mais aluno')),
            },
        ),
    ]
