# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-02 13:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('Email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('turno_aula', models.CharField(max_length=20, verbose_name='Turno')),
                ('senha', models.CharField(max_length=32)),
                ('matricula', models.CharField(max_length=14, unique=True, verbose_name='Matricula')),
            ],
            options={
                'permissions': (('view_aluno', 'Can see aluno'),),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=200, verbose_name='local')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appalunos.Aluno', verbose_name='Aluno')),
            ],
            options={
                'permissions': (('view_relatorio_aluno', 'Can see relatorio aluno'), ('view_relatorioPonto_aluno', 'Can see relatorio mais aluno')),
            },
        ),
    ]
