# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appalunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=14, unique=True, verbose_name='Matricula'),
        ),
    ]
