# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('matrila', models.CharField(max_length=10, unique=True, verbose_name='Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appPonto.Pessoa')),
                ('enderecao', models.CharField(max_length=255, verbose_name='Endereço')),
            ],
            bases=('appPonto.pessoa',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appPonto.Pessoa')),
                ('enderecao', models.CharField(max_length=255, verbose_name='Endereço')),
            ],
            bases=('appPonto.pessoa',),
        ),
    ]
