# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-02 13:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('Email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('matricula', models.CharField(max_length=10, unique=True, verbose_name='Matricula')),
                ('senha', models.CharField(max_length=32)),
            ],
            options={
                'permissions': (('view_funcionario', 'Can see aluno'),),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarPonto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=200, verbose_name='local')),
            ],
            options={
                'permissions': (('view_relatorio', 'Can see relatorio'), ('view_relatorioPonto', 'Can see relatorio a mais')),
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to='appPonto.Funcionario')),
            ],
            options={
                'permissions': (('view_administrador', 'Can see Administrador'),),
            },
            bases=('appPonto.funcionario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='registrarponto',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPonto.Funcionario', verbose_name='Funcionario'),
        ),
    ]
