# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-20 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPonto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appPonto.Pessoa'),
        ),
    ]
