# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-02 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPonto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos', verbose_name='arquivo'),
        ),
    ]
