# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPonto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='matrila',
            new_name='matricula',
        ),
    ]
